[Icon Theme]
Name=ql
Comment=qltheme
Hidden=true
Directories=16x16/devices,16x16/places,24x24/actions,24x24/status,48x48/devices,64x64/apps,64x64/status,scalable/apps

[scalable/apps]
Size=48
Type=Scalable

[64x64/status]
Size=64
Type=Fixed

[64x64/apps]
Size=64
Type=Fixed

[48x48/devices]
Size=48
Type=Fixed

[24x24/status]
Size=24
Type=Fixed

[24x24/actions]
Size=24
Type=Fixed

[16x16/devices]
Size=16
Type=Fixed

[16x16/places]
Size=16
Type=Fixed
