import os

from typing import Union, Any

_pathlike = Union[str, bytes, "os.PathLike[Any]"]

class fsnative(str):
    def __init__(self, object: str = "") -> None: ...

_fsnative = Union[fsnative, str]

def path2fsn(path: _pathlike) -> _fsnative: ...
def fsn2text(path: _fsnative, strict: bool = False) -> str: ...
def text2fsn(text: str) -> _fsnative: ...
def fsn2bytes(path: _fsnative, encoding: str = "utf-8") -> bytes: ...
def bytes2fsn(data: bytes, encoding: str = "utf-8") -> _fsnative: ...
def uri2fsn(uri: str) -> _fsnative: ...
def fsn2uri(path: _fsnative) -> str: ...
def fsn2norm(path: _fsnative) -> _fsnative: ...
def supports_ansi_escape_codes(fd: int) -> bool: ...

print_ = print

def input_(prompt: Any = None) -> _fsnative: ...
