FROM ubuntu:focal

ENV LANG C.UTF-8
ENV PYTHONDONTWRITEBYTECODE 1
ENV DEBIAN_FRONTEND=noninteractive
ENV CI true

RUN apt-get update && apt-get install -y \
    dirmngr \
    && rm -rf /var/lib/apt/lists/*

RUN echo "deb http://ppa.launchpad.net/lazka/dumpingplace/ubuntu focal main" >> /etc/apt/sources.list
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 5806C7C4

RUN apt-get update && apt-get install -y \
    quodlibet \
    exfalso \
    && apt-get install --no-install-recommends -y \
    python3-polib \
    python3-pytest \
    python3-pip \
    python3-setuptools \
    xvfb \
    gettext \
    libxine2 \
    dbus-x11 \
    curl \
    git \
    gdb \
    appstream-util \
    && rm -rf /var/lib/apt/lists/*

RUN python3 -m pip install --upgrade pip && python3 -m pip install --upgrade \
    flake8 \
    xvfbwrapper \
    "coverage[toml]" \
    pytest-faulthandler

ARG HOST_USER_ID=5555
ENV HOST_USER_ID ${HOST_USER_ID}
RUN useradd -u $HOST_USER_ID -ms /bin/bash user

USER user
WORKDIR /home/user
